---
title: "Pacific Groundfish ITQ"
author: "Halley McVeigh"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(janitor)
```

## Read in quota data
```{r}
yr_2011 <- read_csv(here("data", "_Quota_Pound_Price_Data_2011.csv")) %>% 
  clean_names()
yr_2012 <- read_csv(here("data", "_Quota_Pound_Price_Data_2012.csv")) %>% 
  clean_names()
yr_2013 <- read_csv(here("data", "_Quota_Pound_Price_Data_2013.csv")) %>% 
  clean_names()
yr_2014 <- read_csv(here("data", "_Quota_Pound_Price_Data_2014.csv")) %>% 
  clean_names()
yr_2015 <- read_csv(here("data", "_Quota_Pound_Price_Data_2015.csv")) %>% 
  clean_names()
yr_2016 <- read_csv(here("data", "_Quota_Pound_Price_Data_2016.csv")) %>% 
  clean_names()
yr_2017 <- read_csv(here("data", "_Quota_Pound_Price_Data_2017.csv")) %>% 
  clean_names()
yr_2018 <- read_csv(here("data", "_Quota_Pound_Price_Data_2018.csv")) %>% 
  clean_names()
yr_2019 <- read_csv(here("data", "_Quota_Pound_Price_Data_2019.csv")) %>% 
  clean_names()
yr_2020 <- read_csv(here("data", "_Quota_Pound_Price_Data_2020.csv")) %>% 
  clean_names()
yr_2021 <- read_csv(here("data", "_Quota_Pound_Price_Data_2021.csv")) %>% 
  clean_names()



pacific_groundfish_lease <- rbind(yr_2011, yr_2012, yr_2013, yr_2014, yr_2015, yr_2016, yr_2017, yr_2018, yr_2019, yr_2020, yr_2021)
```

## Read in catch data
```{r}
catch_yr_2011 <- read_csv(here("data", "shorebased_ifq_sector_balances_2011.csv")) %>% 
  clean_names()
catch_yr_2012 <- read_csv(here("data", "shorebased_ifq_sector_balances_2012.csv")) %>% 
  clean_names()
catch_yr_2013 <- read_csv(here("data", "shorebased_ifq_sector_balances_2013.csv")) %>% 
  clean_names()
catch_yr_2014 <- read_csv(here("data", "shorebased_ifq_sector_balances_2014.csv")) %>% 
  clean_names()
catch_yr_2015 <- read_csv(here("data", "shorebased_ifq_sector_balances_2015.csv")) %>% 
  clean_names()
catch_yr_2016 <- read_csv(here("data", "shorebased_ifq_sector_balances_2016.csv")) %>% 
  clean_names()
catch_yr_2017 <- read_csv(here("data", "shorebased_ifq_sector_balances_2017.csv")) %>% 
  clean_names()
catch_yr_2018 <- read_csv(here("data", "shorebased_ifq_sector_balances_2018.csv")) %>% 
  clean_names()
catch_yr_2019 <- read_csv(here("data", "shorebased_ifq_sector_balances_2019.csv")) %>% 
  clean_names()
catch_yr_2020 <- read_csv(here("data", "shorebased_ifq_sector_balances_2020.csv")) %>% 
  clean_names()
catch_yr_2021 <- read_csv(here("data", "shorebased_ifq_sector_balances_2021.csv")) %>% 
  clean_names()

pacific_groundfish_catch <- rbind(catch_yr_2011, catch_yr_2012, catch_yr_2013, catch_yr_2014, catch_yr_2015, catch_yr_2016, catch_yr_2017, catch_yr_2018, catch_yr_2019, catch_yr_2020, catch_yr_2021)
```

## Merge catch and lease data for pacific groundfish
```{r}
pacific_groundfish_merge <- merge(pacific_groundfish_lease, pacific_groundfish_catch)

write.csv(pacific_groundfish_merge,"C:\\Users\\halle\\OneDrive\\Desktop\\emLab\\ITQ\\US\\data\\pacific_groundfish_merge.csv")
```

